services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: tickets_db
    ports:
      - "5432:5432"
  
  backend:
    build:
      context: ./backend
    command: sh -c "sleep 10 && npm run createdb && npm run migrate && npm start"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/uploads:/app/uploads
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env.docker
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
    depends_on:
      - backend